// Tokens sourced directly from ../DESIGN.md's YAML frontmatter -- edit
// values there, not here, and keep the two in sync.
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#ffffff',
        surface: '#ffffff',
        'surface-dim': '#f3f4f6',
        'surface-bright': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f9fafb',
        'surface-container': '#f3f4f6',
        'surface-container-high': '#f9fafb',
        'surface-container-highest': '#e5e7eb',
        'surface-variant': '#f3f4f6',
        'on-surface': '#1a1c1c',
        'on-surface-variant': '#71717a',
        'on-background': '#1a1c1c',
        primary: '#1a1c1c',
        'on-primary': '#ffffff',
        'primary-container': '#f3f4f6',
        'on-primary-container': '#1a1c1c',
        secondary: '#454747',
        'on-secondary': '#ffffff',
        'secondary-container': '#e2e2e2',
        'on-secondary-container': '#454747',
        border: '#e5e7eb',
        outline: '#71717a',
        'outline-variant': '#d1d5db',
        accent: '#3E6D8E',
        success: '#00CC52',
        warning: '#d97706',
        error: '#dc2626',
        'on-error': '#ffffff',
        'error-container': '#fee2e2',
        'on-error-container': '#410002',
        'inverse-surface': '#313030',
        'inverse-on-surface': '#f3f4f6',
      },
      borderRadius: {
        DEFAULT: '2px',
        lg: '4px',
        xl: '6px',
        full: '9999px',
      },
      spacing: {
        edge: '1px',
        container: '32px',
        gap: '24px',
        base: '12px',
        'card-gap': '24px',
      },
      fontFamily: {
        'mono-label': ['JetBrains Mono', 'monospace'],
        'mono-sm': ['JetBrains Mono', 'monospace'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'mono-label': ['10px', { lineHeight: '12px', letterSpacing: '0.05em', fontWeight: '500' }],
        'mono-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '400' }],
        'headline-md': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
