// Tokens sourced directly from ../DESIGN.md's YAML frontmatter -- edit
// values there, not here, and keep the two in sync.
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#0A0A0A',
        surface: '#171717',
        'surface-dim': '#141313',
        'surface-bright': '#3a3939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353434',
        'surface-variant': '#353434',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#c4c7c8',
        'on-background': '#e5e2e1',
        primary: '#ffffff',
        'on-primary': '#2f3131',
        'primary-container': '#e2e2e2',
        'on-primary-container': '#636565',
        secondary: '#c7c6c6',
        'on-secondary': '#2f3131',
        'secondary-container': '#484949',
        'on-secondary-container': '#b8b8b8',
        border: '#262626',
        outline: '#8e9192',
        'outline-variant': '#444748',
        accent: '#00FF66',
        success: '#00FF66',
        warning: '#FACC15',
        error: '#EF4444',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '9999px',
      },
      spacing: {
        edge: '1px',
        container: '24px',
        gap: '16px',
        base: '8px',
        'card-gap': '16px',
      },
      fontFamily: {
        'mono-label': ['JetBrains Mono', 'monospace'],
        'mono-sm': ['JetBrains Mono', 'monospace'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'mono-label': ['10px', { lineHeight: '12px', letterSpacing: '0.05em', fontWeight: '500' }],
        'mono-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '400' }],
        'headline-md': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
