import { defineConfig } from 'vite';

export default defineConfig({
  optimizeDeps: {
    // Only scan the main index.html for dependencies, ignoring other .html 
    // files generated by your scrapers or other tools in subdirectories.
    entries: ['index.html']
  }
});
