# -*- coding: utf-8 -*-
# Auto-generated by ai_vision_tracer.py for: Tanner Springs Park
# Image size : 1100 x 660 px
# Scale      : 3.28084 Rhino units per metre
# Diagram BL : (0, 0, 0)  ->  TR : (754.9, 453.0, 0)
# The map image MUST be placed with its bottom-left corner at world origin
# and its top-right at the TR coordinates above.

import rhinoscriptsyntax as rs

LAYER_PLAZA = 'Diagram::Plaza_Boundary'
LAYER_VEG   = 'Diagram::Vegetation'
LAYER_PATHS = 'Diagram::Paths'

def draw_diagram_tanner_springs_park(offset_x=0.0, offset_y=0.0):
    rs.EnableRedraw(False)
    original_layer = rs.CurrentLayer()

    if not rs.IsLayer(LAYER_PLAZA): rs.AddLayer(LAYER_PLAZA)
    rs.CurrentLayer(LAYER_PLAZA)
    pts = [(55.1 + offset_x, 266.8 + offset_y, 0.0), (302.0 + offset_x, 266.8 + offset_y, 0.0), (368.4 + offset_x, 266.8 + offset_y, 0.0), (634.1 + offset_x, 266.8 + offset_y, 0.0), (634.1 + offset_x, 85.6 + offset_y, 0.0), (368.4 + offset_x, 85.6 + offset_y, 0.0), (302.0 + offset_x, 85.6 + offset_y, 0.0), (55.1 + offset_x, 85.6 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_VEG): rs.AddLayer(LAYER_VEG)
    rs.CurrentLayer(LAYER_VEG)
    pts = [(516.4 + offset_x, 364.6 + offset_y, 0.0), (634.1 + offset_x, 364.6 + offset_y, 0.0), (634.1 + offset_x, 270.0 + offset_y, 0.0), (575.3 + offset_x, 270.0 + offset_y, 0.0), (575.3 + offset_x, 293.5 + offset_y, 0.0), (552.6 + offset_x, 293.5 + offset_y, 0.0), (552.6 + offset_x, 323.4 + offset_y, 0.0), (516.4 + offset_x, 323.4 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_VEG): rs.AddLayer(LAYER_VEG)
    rs.CurrentLayer(LAYER_VEG)
    pts = [(302.0 + offset_x, 264.1 + offset_y, 0.0), (324.6 + offset_x, 264.1 + offset_y, 0.0), (324.6 + offset_x, 246.4 + offset_y, 0.0), (302.0 + offset_x, 246.4 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_VEG): rs.AddLayer(LAYER_VEG)
    rs.CurrentLayer(LAYER_VEG)
    pts = [(55.1 + offset_x, 284.9 + offset_y, 0.0), (272.5 + offset_x, 284.9 + offset_y, 0.0), (272.5 + offset_x, 270.0 + offset_y, 0.0), (55.1 + offset_x, 270.0 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_VEG): rs.AddLayer(LAYER_VEG)
    rs.CurrentLayer(LAYER_VEG)
    pts = [(55.1 + offset_x, 101.9 + offset_y, 0.0), (272.5 + offset_x, 101.9 + offset_y, 0.0), (272.5 + offset_x, 87.4 + offset_y, 0.0), (55.1 + offset_x, 87.4 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_VEG): rs.AddLayer(LAYER_VEG)
    rs.CurrentLayer(LAYER_VEG)
    pts = [(368.4 + offset_x, 101.9 + offset_y, 0.0), (597.1 + offset_x, 101.9 + offset_y, 0.0), (597.1 + offset_x, 87.4 + offset_y, 0.0), (368.4 + offset_x, 87.4 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_VEG): rs.AddLayer(LAYER_VEG)
    rs.CurrentLayer(LAYER_VEG)
    pts = [(634.1 + offset_x, 181.6 + offset_y, 0.0), (677.9 + offset_x, 181.6 + offset_y, 0.0), (677.9 + offset_x, 140.4 + offset_y, 0.0), (634.1 + offset_x, 140.4 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(55.1 + offset_x, 266.8 + offset_y, 0.0), (634.1 + offset_x, 266.8 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(55.1 + offset_x, 85.6 + offset_y, 0.0), (634.1 + offset_x, 85.6 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(302.0 + offset_x, 362.4 + offset_y, 0.0), (302.0 + offset_x, 266.8 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(368.4 + offset_x, 362.4 + offset_y, 0.0), (368.4 + offset_x, 266.8 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(302.0 + offset_x, 85.6 + offset_y, 0.0), (302.0 + offset_x, 0.0 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(368.4 + offset_x, 85.6 + offset_y, 0.0), (368.4 + offset_x, 0.0 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(634.1 + offset_x, 362.4 + offset_y, 0.0), (634.1 + offset_x, 266.8 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(634.1 + offset_x, 226.5 + offset_y, 0.0), (634.1 + offset_x, 181.6 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(324.6 + offset_x, 249.6 + offset_y, 0.0), (368.4 + offset_x, 249.6 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(302.0 + offset_x, 105.1 + offset_y, 0.0), (368.4 + offset_x, 105.1 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(302.0 + offset_x, 237.8 + offset_y, 0.0), (302.0 + offset_x, 105.1 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(368.4 + offset_x, 237.8 + offset_y, 0.0), (368.4 + offset_x, 105.1 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    rs.CurrentLayer(original_layer)
    rs.EnableRedraw(True)
    print('Diagram drawn for Tanner Springs Park.')


# --- Run immediately when executed via RunPythonScript ---
draw_diagram_tanner_springs_park()