# -*- coding: utf-8 -*-
# Auto-generated by ai_vision_tracer.py for: Piazza del Campo
# Image size : 1100 x 660 px
# Scale      : 3.28084 Rhino units per metre
# Diagram BL : (0, 0, 0)  ->  TR : (1568.0, 940.8, 0)
# The map image MUST be placed with its bottom-left corner at world origin
# and its top-right at the TR coordinates above.

import rhinoscriptsyntax as rs

LAYER_PLAZA = 'Diagram::Plaza_Boundary'
LAYER_VEG   = 'Diagram::Vegetation'
LAYER_PATHS = 'Diagram::Paths'

def draw_diagram_piazza_del_campo(offset_x=0.0, offset_y=0.0):
    rs.EnableRedraw(False)
    original_layer = rs.CurrentLayer()

    rs.CurrentLayer(original_layer)
    rs.EnableRedraw(True)
    print('Diagram drawn for Piazza del Campo.')


# --- Run immediately when executed via RunPythonScript ---
draw_diagram_piazza_del_campo()