# -*- coding: utf-8 -*-
# Auto-generated by ai_vision_tracer.py for: Schouwburgplein
# Image size : 1100 x 660 px
# Scale      : 3.28084 Rhino units per metre
# Diagram BL : (0, 0, 0)  ->  TR : (1329.1, 797.5, 0)
# The map image MUST be placed with its bottom-left corner at world origin
# and its top-right at the TR coordinates above.

import rhinoscriptsyntax as rs

LAYER_PLAZA = 'Diagram::Plaza_Boundary'
LAYER_VEG   = 'Diagram::Vegetation'
LAYER_PATHS = 'Diagram::Paths'

def draw_diagram_schouwburgplein(offset_x=0.0, offset_y=0.0):
    rs.EnableRedraw(False)
    original_layer = rs.CurrentLayer()

    if not rs.IsLayer(LAYER_PLAZA): rs.AddLayer(LAYER_PLAZA)
    rs.CurrentLayer(LAYER_PLAZA)
    pts = [(818.2 + offset_x, 567.9 + offset_y, 0.0), (818.2 + offset_x, 502.6 + offset_y, 0.0), (818.2 + offset_x, 329.6 + offset_y, 0.0), (762.4 + offset_x, 329.6 + offset_y, 0.0), (762.4 + offset_x, 312.2 + offset_y, 0.0), (567.7 + offset_x, 312.2 + offset_y, 0.0), (567.7 + offset_x, 305.5 + offset_y, 0.0), (477.6 + offset_x, 305.5 + offset_y, 0.0), (468.5 + offset_x, 294.8 + offset_y, 0.0), (441.5 + offset_x, 352.8 + offset_y, 0.0), (432.5 + offset_x, 410.9 + offset_y, 0.0), (441.5 + offset_x, 497.8 + offset_y, 0.0), (450.6 + offset_x, 502.6 + offset_y, 0.0), (450.6 + offset_x, 517.2 + offset_y, 0.0), (468.5 + offset_x, 517.2 + offset_y, 0.0), (630.8 + offset_x, 517.2 + offset_y, 0.0), (811.0 + offset_x, 521.9 + offset_y, 0.0), (818.2 + offset_x, 526.8 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_VEG): rs.AddLayer(LAYER_VEG)
    rs.CurrentLayer(LAYER_VEG)
    pts = [(0.0 + offset_x, 454.3 + offset_y, 0.0), (175.7 + offset_x, 570.4 + offset_y, 0.0), (261.3 + offset_x, 531.7 + offset_y, 0.0), (306.4 + offset_x, 435.0 + offset_y, 0.0), (279.4 + offset_x, 333.5 + offset_y, 0.0), (229.8 + offset_x, 217.5 + offset_y, 0.0), (180.2 + offset_x, 111.2 + offset_y, 0.0), (135.2 + offset_x, 24.2 + offset_y, 0.0), (0.0 + offset_x, 4.9 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_VEG): rs.AddLayer(LAYER_VEG)
    rs.CurrentLayer(LAYER_VEG)
    pts = [(635.3 + offset_x, 381.8 + offset_y, 0.0), (756.9 + offset_x, 381.8 + offset_y, 0.0), (756.9 + offset_x, 314.1 + offset_y, 0.0), (635.3 + offset_x, 314.1 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_VEG): rs.AddLayer(LAYER_VEG)
    rs.CurrentLayer(LAYER_VEG)
    pts = [(558.6 + offset_x, 294.8 + offset_y, 0.0), (576.7 + offset_x, 294.8 + offset_y, 0.0), (576.7 + offset_x, 275.5 + offset_y, 0.0), (558.6 + offset_x, 275.5 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_VEG): rs.AddLayer(LAYER_VEG)
    rs.CurrentLayer(LAYER_VEG)
    pts = [(549.7 + offset_x, 478.5 + offset_y, 0.0), (576.7 + offset_x, 478.5 + offset_y, 0.0), (576.7 + offset_x, 459.2 + offset_y, 0.0), (549.7 + offset_x, 459.2 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_VEG): rs.AddLayer(LAYER_VEG)
    rs.CurrentLayer(LAYER_VEG)
    pts = [(270.3 + offset_x, 700.8 + offset_y, 0.0), (288.3 + offset_x, 749.1 + offset_y, 0.0), (180.2 + offset_x, 797.5 + offset_y, 0.0), (0.0 + offset_x, 797.5 + offset_y, 0.0), (0.0 + offset_x, 633.1 + offset_y, 0.0), (135.2 + offset_x, 633.1 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(432.5 + offset_x, 314.1 + offset_y, 0.0), (495.6 + offset_x, 362.5 + offset_y, 0.0), (594.8 + offset_x, 410.9 + offset_y, 0.0), (675.9 + offset_x, 459.2 + offset_y, 0.0), (766.0 + offset_x, 507.5 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(585.7 + offset_x, 314.1 + offset_y, 0.0), (585.7 + offset_x, 410.9 + offset_y, 0.0), (585.7 + offset_x, 507.5 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(45.1 + offset_x, 72.5 + offset_y, 0.0), (90.1 + offset_x, 169.1 + offset_y, 0.0), (162.2 + offset_x, 314.1 + offset_y, 0.0), (225.3 + offset_x, 430.2 + offset_y, 0.0), (180.2 + offset_x, 526.8 + offset_y, 0.0), (90.1 + offset_x, 623.5 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    rs.CurrentLayer(original_layer)
    rs.EnableRedraw(True)
    print('Diagram drawn for Schouwburgplein.')


# --- Run immediately when executed via RunPythonScript ---
draw_diagram_schouwburgplein()