# -*- coding: utf-8 -*-
# Auto-generated by ai_vision_tracer.py for: Zaryadye Park
# Image size : 1100 x 660 px
# Scale      : 3.28084 Rhino units per metre
# Diagram BL : (0, 0, 0)  ->  TR : (2425.8, 1455.5, 0)
# The map image MUST be placed with its bottom-left corner at world origin
# and its top-right at the TR coordinates above.

import rhinoscriptsyntax as rs

LAYER_PLAZA  = 'BOUNDARY'
LAYER_VEG   = 'GREEN SPACE'
LAYER_PATHS = 'PEDESTRIAN PATH'
LAYER_STREET = 'STREET'

def draw_diagram_zaryadye_park(offset_x=0.0, offset_y=0.0):
    rs.EnableRedraw(False)
    original_layer = rs.CurrentLayer()

    if not rs.IsLayer(LAYER_PLAZA): rs.AddLayer(LAYER_PLAZA)
    rs.CurrentLayer(LAYER_PLAZA)
    pts = [(625.8 + offset_x, 1235.7 + offset_y, 0.0), (468.2 + offset_x, 1180.4 + offset_y, 0.0), (344.5 + offset_x, 1075.6 + offset_y, 0.0), (315.3 + offset_x, 903.8 + offset_y, 0.0), (305.6 + offset_x, 716.1 + offset_y, 0.0), (310.5 + offset_x, 553.1 + offset_y, 0.0), (344.5 + offset_x, 468.7 + offset_y, 0.0), (419.7 + offset_x, 426.4 + offset_y, 0.0), (511.8 + offset_x, 409.0 + offset_y, 0.0), (606.4 + offset_x, 409.0 + offset_y, 0.0), (686.5 + offset_x, 432.3 + offset_y, 0.0), (766.5 + offset_x, 493.4 + offset_y, 0.0), (800.5 + offset_x, 557.4 + offset_y, 0.0), (819.9 + offset_x, 647.7 + offset_y, 0.0), (844.2 + offset_x, 768.5 + offset_y, 0.0), (829.6 + offset_x, 879.1 + offset_y, 0.0), (805.4 + offset_x, 969.3 + offset_y, 0.0), (773.8 + offset_x, 1062.5 + offset_y, 0.0), (713.2 + offset_x, 1141.1 + offset_y, 0.0), (625.8 + offset_x, 1235.7 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_VEG): rs.AddLayer(LAYER_VEG)
    rs.CurrentLayer(LAYER_VEG)
    pts = [(936.3 + offset_x, 1244.4 + offset_y, 0.0), (989.7 + offset_x, 1292.4 + offset_y, 0.0), (1064.9 + offset_x, 1279.3 + offset_y, 0.0), (1113.4 + offset_x, 1213.9 + offset_y, 0.0), (1091.6 + offset_x, 1149.8 + offset_y, 0.0), (994.6 + offset_x, 1119.2 + offset_y, 0.0), (936.3 + offset_x, 1244.4 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_VEG): rs.AddLayer(LAYER_VEG)
    rs.CurrentLayer(LAYER_VEG)
    pts = [(1164.4 + offset_x, 1228.4 + offset_y, 0.0), (1263.8 + offset_x, 1295.4 + offset_y, 0.0), (1382.7 + offset_x, 1272.1 + offset_y, 0.0), (1453.0 + offset_x, 1215.3 + offset_y, 0.0), (1516.1 + offset_x, 1135.3 + offset_y, 0.0), (1508.8 + offset_x, 1055.2 + offset_y, 0.0), (1421.5 + offset_x, 991.2 + offset_y, 0.0), (1341.4 + offset_x, 975.2 + offset_y, 0.0), (1232.3 + offset_x, 991.2 + offset_y, 0.0), (1164.4 + offset_x, 1135.3 + offset_y, 0.0), (1164.4 + offset_x, 1228.4 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_VEG): rs.AddLayer(LAYER_VEG)
    rs.CurrentLayer(LAYER_VEG)
    pts = [(904.8 + offset_x, 944.6 + offset_y, 0.0), (963.0 + offset_x, 1021.7 + offset_y, 0.0), (1057.6 + offset_x, 1047.9 + offset_y, 0.0), (1183.8 + offset_x, 1014.5 + offset_y, 0.0), (1244.4 + offset_x, 911.1 + offset_y, 0.0), (1239.6 + offset_x, 790.3 + offset_y, 0.0), (1169.2 + offset_x, 701.5 + offset_y, 0.0), (1050.4 + offset_x, 669.5 + offset_y, 0.0), (931.5 + offset_x, 710.3 + offset_y, 0.0), (875.7 + offset_x, 815.1 + offset_y, 0.0), (904.8 + offset_x, 944.6 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_VEG): rs.AddLayer(LAYER_VEG)
    rs.CurrentLayer(LAYER_VEG)
    pts = [(1278.4 + offset_x, 879.1 + offset_y, 0.0), (1341.4 + offset_x, 966.4 + offset_y, 0.0), (1484.6 + offset_x, 991.2 + offset_y, 0.0), (1596.2 + offset_x, 959.1 + offset_y, 0.0), (1649.5 + offset_x, 879.1 + offset_y, 0.0), (1627.7 + offset_x, 781.6 + offset_y, 0.0), (1547.6 + offset_x, 701.5 + offset_y, 0.0), (1421.5 + offset_x, 685.5 + offset_y, 0.0), (1309.9 + offset_x, 749.6 + offset_y, 0.0), (1278.4 + offset_x, 879.1 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_VEG): rs.AddLayer(LAYER_VEG)
    rs.CurrentLayer(LAYER_VEG)
    pts = [(897.5 + offset_x, 633.1 + offset_y, 0.0), (946.0 + offset_x, 678.2 + offset_y, 0.0), (1057.6 + offset_x, 701.5 + offset_y, 0.0), (1161.9 + offset_x, 669.5 + offset_y, 0.0), (1232.3 + offset_x, 621.5 + offset_y, 0.0), (1246.8 + offset_x, 525.4 + offset_y, 0.0), (1183.8 + offset_x, 461.4 + offset_y, 0.0), (1057.6 + offset_x, 445.4 + offset_y, 0.0), (946.0 + offset_x, 493.4 + offset_y, 0.0), (892.7 + offset_x, 557.4 + offset_y, 0.0), (897.5 + offset_x, 633.1 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_VEG): rs.AddLayer(LAYER_VEG)
    rs.CurrentLayer(LAYER_VEG)
    pts = [(1263.8 + offset_x, 573.5 + offset_y, 0.0), (1295.4 + offset_x, 653.5 + offset_y, 0.0), (1390.0 + offset_x, 685.5 + offset_y, 0.0), (1530.7 + offset_x, 669.5 + offset_y, 0.0), (1673.8 + offset_x, 637.5 + offset_y, 0.0), (1770.8 + offset_x, 589.5 + offset_y, 0.0), (1863.0 + offset_x, 525.4 + offset_y, 0.0), (1957.6 + offset_x, 461.4 + offset_y, 0.0), (2020.7 + offset_x, 397.3 + offset_y, 0.0), (1894.5 + offset_x, 349.3 + offset_y, 0.0), (1736.8 + offset_x, 333.3 + offset_y, 0.0), (1579.2 + offset_x, 349.3 + offset_y, 0.0), (1421.5 + offset_x, 397.3 + offset_y, 0.0), (1309.9 + offset_x, 477.4 + offset_y, 0.0), (1263.8 + offset_x, 573.5 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_VEG): rs.AddLayer(LAYER_VEG)
    rs.CurrentLayer(LAYER_VEG)
    pts = [(1690.8 + offset_x, 781.6 + offset_y, 0.0), (1785.4 + offset_x, 749.6 + offset_y, 0.0), (1894.5 + offset_x, 701.5 + offset_y, 0.0), (1989.1 + offset_x, 653.5 + offset_y, 0.0), (2083.7 + offset_x, 605.5 + offset_y, 0.0), (2178.3 + offset_x, 557.4 + offset_y, 0.0), (2275.4 + offset_x, 509.4 + offset_y, 0.0), (2353.0 + offset_x, 478.8 + offset_y, 0.0), (2209.9 + offset_x, 381.3 + offset_y, 0.0), (2052.2 + offset_x, 461.4 + offset_y, 0.0), (1894.5 + offset_x, 541.4 + offset_y, 0.0), (1736.8 + offset_x, 621.5 + offset_y, 0.0), (1690.8 + offset_x, 781.6 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(802.9 + offset_x, 1007.2 + offset_y, 0.0), (851.4 + offset_x, 975.2 + offset_y, 0.0), (916.9 + offset_x, 946.0 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(1074.6 + offset_x, 1023.2 + offset_y, 0.0), (1137.7 + offset_x, 943.1 + offset_y, 0.0), (1183.8 + offset_x, 847.1 + offset_y, 0.0), (1200.8 + offset_x, 749.6 + offset_y, 0.0), (1200.8 + offset_x, 653.5 + offset_y, 0.0), (1215.3 + offset_x, 573.5 + offset_y, 0.0), (1246.8 + offset_x, 493.4 + offset_y, 0.0), (1295.4 + offset_x, 429.4 + offset_y, 0.0), (1341.4 + offset_x, 397.3 + offset_y, 0.0), (1421.5 + offset_x, 381.3 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(1358.4 + offset_x, 943.1 + offset_y, 0.0), (1436.1 + offset_x, 1007.2 + offset_y, 0.0), (1562.2 + offset_x, 991.2 + offset_y, 0.0), (1642.2 + offset_x, 925.7 + offset_y, 0.0), (1673.8 + offset_x, 847.1 + offset_y, 0.0), (1659.2 + offset_x, 765.6 + offset_y, 0.0), (1562.2 + offset_x, 701.5 + offset_y, 0.0), (1436.1 + offset_x, 685.5 + offset_y, 0.0), (1326.9 + offset_x, 749.6 + offset_y, 0.0), (1278.4 + offset_x, 847.1 + offset_y, 0.0), (1358.4 + offset_x, 943.1 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(1421.5 + offset_x, 381.3 + offset_y, 0.0), (1499.1 + offset_x, 365.3 + offset_y, 0.0), (1579.2 + offset_x, 349.3 + offset_y, 0.0), (1659.2 + offset_x, 333.3 + offset_y, 0.0), (1736.8 + offset_x, 317.3 + offset_y, 0.0), (1816.9 + offset_x, 301.3 + offset_y, 0.0), (1894.5 + offset_x, 294.0 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(946.0 + offset_x, 1295.4 + offset_y, 0.0), (1011.5 + offset_x, 1215.3 + offset_y, 0.0), (1074.6 + offset_x, 1135.3 + offset_y, 0.0), (1106.1 + offset_x, 1055.2 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(1246.8 + offset_x, 911.1 + offset_y, 0.0), (1278.4 + offset_x, 879.1 + offset_y, 0.0), (1341.4 + offset_x, 895.1 + offset_y, 0.0), (1358.4 + offset_x, 943.1 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(1421.5 + offset_x, 1039.2 + offset_y, 0.0), (1530.7 + offset_x, 1071.2 + offset_y, 0.0), (1659.2 + offset_x, 1055.2 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(1690.8 + offset_x, 685.5 + offset_y, 0.0), (1770.8 + offset_x, 653.5 + offset_y, 0.0), (1863.0 + offset_x, 621.5 + offset_y, 0.0), (1957.6 + offset_x, 589.5 + offset_y, 0.0), (2052.2 + offset_x, 557.4 + offset_y, 0.0), (2146.8 + offset_x, 525.4 + offset_y, 0.0), (2243.8 + offset_x, 493.4 + offset_y, 0.0), (2338.4 + offset_x, 461.4 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(805.4 + offset_x, 621.5 + offset_y, 0.0), (836.9 + offset_x, 653.5 + offset_y, 0.0), (900.0 + offset_x, 669.5 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    rs.CurrentLayer(original_layer)
    rs.EnableRedraw(True)
    print('Diagram drawn for Zaryadye Park.')


# --- Run immediately when executed via RunPythonScript ---
draw_diagram_zaryadye_park()