# -*- coding: utf-8 -*-
# Auto-generated by ai_vision_tracer.py for: Millennium Park
# Image size : 1100 x 660 px
# Scale      : 3.28084 Rhino units per metre
# Diagram BL : (0, 0, 0)  ->  TR : (3209.0, 1925.4, 0)
# The map image MUST be placed with its bottom-left corner at world origin
# and its top-right at the TR coordinates above.

import rhinoscriptsyntax as rs

LAYER_PLAZA = 'Diagram::Plaza_Boundary'
LAYER_VEG   = 'Diagram::Vegetation'
LAYER_PATHS = 'Diagram::Paths'

def draw_diagram_millennium_park(offset_x=0.0, offset_y=0.0):
    rs.EnableRedraw(False)
    original_layer = rs.CurrentLayer()

    if not rs.IsLayer(LAYER_PLAZA): rs.AddLayer(LAYER_PLAZA)
    rs.CurrentLayer(LAYER_PLAZA)
    pts = [(930.6 + offset_x, 1709.8 + offset_y, 0.0), (1922.2 + offset_x, 1709.8 + offset_y, 0.0), (1922.2 + offset_x, 192.5 + offset_y, 0.0), (930.6 + offset_x, 192.5 + offset_y, 0.0), (930.6 + offset_x, 1709.8 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_VEG): rs.AddLayer(LAYER_VEG)
    rs.CurrentLayer(LAYER_VEG)
    pts = [(1922.2 + offset_x, 1709.8 + offset_y, 0.0), (2172.5 + offset_x, 1709.8 + offset_y, 0.0), (2268.8 + offset_x, 1671.3 + offset_y, 0.0), (2458.1 + offset_x, 1594.2 + offset_y, 0.0), (2625.0 + offset_x, 1517.2 + offset_y, 0.0), (2769.4 + offset_x, 1417.1 + offset_y, 0.0), (2913.8 + offset_x, 1213.0 + offset_y, 0.0), (3032.5 + offset_x, 1008.9 + offset_y, 0.0), (3055.0 + offset_x, 854.9 + offset_y, 0.0), (3032.5 + offset_x, 702.8 + offset_y, 0.0), (2936.3 + offset_x, 498.7 + offset_y, 0.0), (2817.5 + offset_x, 346.6 + offset_y, 0.0), (2625.0 + offset_x, 244.5 + offset_y, 0.0), (2342.6 + offset_x, 192.5 + offset_y, 0.0), (1922.2 + offset_x, 192.5 + offset_y, 0.0), (1922.2 + offset_x, 1709.8 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_VEG): rs.AddLayer(LAYER_VEG)
    rs.CurrentLayer(LAYER_VEG)
    pts = [(943.5 + offset_x, 1619.3 + offset_y, 0.0), (1087.9 + offset_x, 1619.3 + offset_y, 0.0), (1087.9 + offset_x, 1288.1 + offset_y, 0.0), (943.5 + offset_x, 1288.1 + offset_y, 0.0), (943.5 + offset_x, 1619.3 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_VEG): rs.AddLayer(LAYER_VEG)
    rs.CurrentLayer(LAYER_VEG)
    pts = [(943.5 + offset_x, 1263.1 + offset_y, 0.0), (1087.9 + offset_x, 1263.1 + offset_y, 0.0), (1087.9 + offset_x, 625.8 + offset_y, 0.0), (943.5 + offset_x, 625.8 + offset_y, 0.0), (943.5 + offset_x, 1263.1 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_VEG): rs.AddLayer(LAYER_VEG)
    rs.CurrentLayer(LAYER_VEG)
    pts = [(943.5 + offset_x, 600.7 + offset_y, 0.0), (1087.9 + offset_x, 600.7 + offset_y, 0.0), (1087.9 + offset_x, 269.6 + offset_y, 0.0), (943.5 + offset_x, 269.6 + offset_y, 0.0), (943.5 + offset_x, 600.7 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_VEG): rs.AddLayer(LAYER_VEG)
    rs.CurrentLayer(LAYER_VEG)
    pts = [(1431.2 + offset_x, 1619.3 + offset_y, 0.0), (1896.5 + offset_x, 1619.3 + offset_y, 0.0), (1896.5 + offset_x, 1288.1 + offset_y, 0.0), (1431.2 + offset_x, 1288.1 + offset_y, 0.0), (1431.2 + offset_x, 1619.3 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_VEG): rs.AddLayer(LAYER_VEG)
    rs.CurrentLayer(LAYER_VEG)
    pts = [(1431.2 + offset_x, 1263.1 + offset_y, 0.0), (1896.5 + offset_x, 1263.1 + offset_y, 0.0), (1896.5 + offset_x, 625.8 + offset_y, 0.0), (1431.2 + offset_x, 625.8 + offset_y, 0.0), (1431.2 + offset_x, 1263.1 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_VEG): rs.AddLayer(LAYER_VEG)
    rs.CurrentLayer(LAYER_VEG)
    pts = [(1120.0 + offset_x, 244.5 + offset_y, 0.0), (1408.8 + offset_x, 244.5 + offset_y, 0.0), (1408.8 + offset_x, 192.5 + offset_y, 0.0), (1120.0 + offset_x, 192.5 + offset_y, 0.0), (1120.0 + offset_x, 244.5 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(1408.8 + offset_x, 1213.0 + offset_y, 0.0), (1456.9 + offset_x, 1238.0 + offset_y, 0.0), (1505.0 + offset_x, 1263.1 + offset_y, 0.0), (1553.2 + offset_x, 1276.6 + offset_y, 0.0), (1601.3 + offset_x, 1276.6 + offset_y, 0.0), (1671.9 + offset_x, 1263.1 + offset_y, 0.0), (1742.5 + offset_x, 1224.6 + offset_y, 0.0), (1813.1 + offset_x, 1174.5 + offset_y, 0.0), (1886.9 + offset_x, 1111.0 + offset_y, 0.0), (1935.0 + offset_x, 1059.0 + offset_y, 0.0), (1970.3 + offset_x, 1008.9 + offset_y, 0.0), (1992.8 + offset_x, 956.9 + offset_y, 0.0), (1992.8 + offset_x, 906.9 + offset_y, 0.0), (1970.3 + offset_x, 854.9 + offset_y, 0.0), (1935.0 + offset_x, 804.8 + offset_y, 0.0), (1886.9 + offset_x, 754.8 + offset_y, 0.0), (1813.1 + offset_x, 716.3 + offset_y, 0.0), (1742.5 + offset_x, 677.7 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(1171.3 + offset_x, 1238.0 + offset_y, 0.0), (1219.4 + offset_x, 1238.0 + offset_y, 0.0), (1264.4 + offset_x, 1238.0 + offset_y, 0.0), (1312.5 + offset_x, 1238.0 + offset_y, 0.0), (1386.3 + offset_x, 1238.0 + offset_y, 0.0), (1386.3 + offset_x, 906.9 + offset_y, 0.0), (1386.3 + offset_x, 652.7 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(1094.3 + offset_x, 1632.8 + offset_y, 0.0), (1094.3 + offset_x, 1276.6 + offset_y, 0.0), (1094.3 + offset_x, 1213.0 + offset_y, 0.0), (1094.3 + offset_x, 614.2 + offset_y, 0.0), (1094.3 + offset_x, 258.0 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(1120.0 + offset_x, 1186.1 + offset_y, 0.0), (1145.6 + offset_x, 1161.0 + offset_y, 0.0), (1171.3 + offset_x, 1136.0 + offset_y, 0.0), (1193.8 + offset_x, 1111.0 + offset_y, 0.0), (1219.4 + offset_x, 1136.0 + offset_y, 0.0), (1241.9 + offset_x, 1161.0 + offset_y, 0.0), (1264.4 + offset_x, 1186.1 + offset_y, 0.0), (1241.9 + offset_x, 1213.0 + offset_y, 0.0), (1219.4 + offset_x, 1238.0 + offset_y, 0.0), (1193.8 + offset_x, 1263.1 + offset_y, 0.0), (1171.3 + offset_x, 1238.0 + offset_y, 0.0), (1145.6 + offset_x, 1213.0 + offset_y, 0.0), (1120.0 + offset_x, 1186.1 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(1097.5 + offset_x, 614.2 + offset_y, 0.0), (1097.5 + offset_x, 462.1 + offset_y, 0.0), (1264.4 + offset_x, 462.1 + offset_y, 0.0), (1264.4 + offset_x, 614.2 + offset_y, 0.0), (1097.5 + offset_x, 614.2 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(1742.5 + offset_x, 677.7 + offset_y, 0.0), (1861.2 + offset_x, 600.7 + offset_y, 0.0), (1983.2 + offset_x, 525.6 + offset_y, 0.0), (2101.9 + offset_x, 448.6 + offset_y, 0.0), (2220.7 + offset_x, 371.6 + offset_y, 0.0), (2342.6 + offset_x, 321.5 + offset_y, 0.0), (2506.3 + offset_x, 346.6 + offset_y, 0.0), (2698.8 + offset_x, 498.7 + offset_y, 0.0), (2865.7 + offset_x, 702.8 + offset_y, 0.0), (3010.1 + offset_x, 906.9 + offset_y, 0.0), (3032.5 + offset_x, 1111.0 + offset_y, 0.0), (2913.8 + offset_x, 1315.1 + offset_y, 0.0), (2746.9 + offset_x, 1517.2 + offset_y, 0.0), (2580.1 + offset_x, 1671.3 + offset_y, 0.0), (2387.5 + offset_x, 1709.8 + offset_y, 0.0), (2195.0 + offset_x, 1671.3 + offset_y, 0.0), (2028.1 + offset_x, 1569.2 + offset_y, 0.0), (1886.9 + offset_x, 1467.2 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    rs.CurrentLayer(original_layer)
    rs.EnableRedraw(True)
    print('Diagram drawn for Millennium Park.')


# --- Run immediately when executed via RunPythonScript ---
draw_diagram_millennium_park()