# -*- coding: utf-8 -*-
# Auto-generated by ai_vision_tracer.py for: Paley Park
# Image size : 1100 x 660 px
# Scale      : 3.28084 Rhino units per metre
# Diagram BL : (0, 0, 0)  ->  TR : (816.2, 489.7, 0)
# The map image MUST be placed with its bottom-left corner at world origin
# and its top-right at the TR coordinates above.

import rhinoscriptsyntax as rs

LAYER_PLAZA = 'Diagram::Plaza_Boundary'
LAYER_VEG   = 'Diagram::Vegetation'
LAYER_PATHS = 'Diagram::Paths'

def draw_diagram_paley_park(offset_x=0.0, offset_y=0.0):
    rs.EnableRedraw(False)
    original_layer = rs.CurrentLayer()

    if not rs.IsLayer(LAYER_PLAZA): rs.AddLayer(LAYER_PLAZA)
    rs.CurrentLayer(LAYER_PLAZA)
    pts = [(310.2 + offset_x, 213.0 + offset_y, 0.0), (481.6 + offset_x, 237.0 + offset_y, 0.0), (484.0 + offset_x, 208.6 + offset_y, 0.0), (500.3 + offset_x, 182.2 + offset_y, 0.0), (510.1 + offset_x, 157.2 + offset_y, 0.0), (516.7 + offset_x, 126.3 + offset_y, 0.0), (522.4 + offset_x, 97.9 + offset_y, 0.0), (271.8 + offset_x, 87.7 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_VEG): rs.AddLayer(LAYER_VEG)
    rs.CurrentLayer(LAYER_VEG)
    pts = [(120.0 + offset_x, 489.7 + offset_y, 0.0), (141.2 + offset_x, 489.7 + offset_y, 0.0), (165.7 + offset_x, 232.1 + offset_y, 0.0), (141.2 + offset_x, 232.1 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_VEG): rs.AddLayer(LAYER_VEG)
    rs.CurrentLayer(LAYER_VEG)
    pts = [(138.8 + offset_x, 219.9 + offset_y, 0.0), (163.2 + offset_x, 221.8 + offset_y, 0.0), (190.2 + offset_x, 91.1 + offset_y, 0.0), (165.7 + offset_x, 87.7 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_VEG): rs.AddLayer(LAYER_VEG)
    rs.CurrentLayer(LAYER_VEG)
    pts = [(163.2 + offset_x, 79.8 + offset_y, 0.0), (187.7 + offset_x, 81.8 + offset_y, 0.0), (206.5 + offset_x, 1.0 + offset_y, 0.0), (182.0 + offset_x, 1.0 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_VEG): rs.AddLayer(LAYER_VEG)
    rs.CurrentLayer(LAYER_VEG)
    pts = [(271.8 + offset_x, 87.7 + offset_y, 0.0), (277.5 + offset_x, 73.9 + offset_y, 0.0), (306.1 + offset_x, 79.8 + offset_y, 0.0), (310.2 + offset_x, 87.7 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(75.1 + offset_x, 489.7 + offset_y, 0.0), (95.5 + offset_x, 233.6 + offset_y, 0.0), (122.4 + offset_x, 1.0 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(142.8 + offset_x, 489.7 + offset_y, 0.0), (167.3 + offset_x, 232.1 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(163.2 + offset_x, 221.8 + offset_y, 0.0), (190.2 + offset_x, 91.1 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(187.7 + offset_x, 81.8 + offset_y, 0.0), (209.8 + offset_x, 1.0 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(271.8 + offset_x, 221.8 + offset_y, 0.0), (408.1 + offset_x, 244.9 + offset_y, 0.0), (748.5 + offset_x, 313.4 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(310.2 + offset_x, 213.0 + offset_y, 0.0), (481.6 + offset_x, 237.0 + offset_y, 0.0), (679.9 + offset_x, 267.9 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(106.1 + offset_x, 239.0 + offset_y, 0.0), (149.4 + offset_x, 239.0 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(128.1 + offset_x, 227.7 + offset_y, 0.0), (169.8 + offset_x, 227.7 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(149.4 + offset_x, 91.1 + offset_y, 0.0), (190.2 + offset_x, 91.1 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(271.8 + offset_x, 224.3 + offset_y, 0.0), (306.1 + offset_x, 218.9 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    rs.CurrentLayer(original_layer)
    rs.EnableRedraw(True)
    print('Diagram drawn for Paley Park.')


# --- Run immediately when executed via RunPythonScript ---
draw_diagram_paley_park()