# -*- coding: utf-8 -*-
# Auto-generated by ai_vision_tracer.py for: Klyde Warren Park
# Image size : 1100 x 660 px
# Scale      : 3.28084 Rhino units per metre
# Diagram BL : (0, 0, 0)  ->  TR : (2562.2, 1537.3, 0)
# The map image MUST be placed with its bottom-left corner at world origin
# and its top-right at the TR coordinates above.

import rhinoscriptsyntax as rs

LAYER_PLAZA = 'Diagram::Plaza_Boundary'
LAYER_VEG   = 'Diagram::Vegetation'
LAYER_PATHS = 'Diagram::Paths'

def draw_diagram_klyde_warren_park(offset_x=0.0, offset_y=0.0):
    rs.EnableRedraw(False)
    original_layer = rs.CurrentLayer()

    if not rs.IsLayer(LAYER_PLAZA): rs.AddLayer(LAYER_PLAZA)
    rs.CurrentLayer(LAYER_PLAZA)
    pts = [(1037.7 + offset_x, 851.7 + offset_y, 0.0), (1975.4 + offset_x, 956.2 + offset_y, 0.0), (2039.5 + offset_x, 445.8 + offset_y, 0.0), (1037.7 + offset_x, 364.3 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_VEG): rs.AddLayer(LAYER_VEG)
    rs.CurrentLayer(LAYER_VEG)
    pts = [(1150.4 + offset_x, 747.1 + offset_y, 0.0), (1450.2 + offset_x, 782.5 + offset_y, 0.0), (1475.8 + offset_x, 562.7 + offset_y, 0.0), (1176.0 + offset_x, 527.3 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_VEG): rs.AddLayer(LAYER_VEG)
    rs.CurrentLayer(LAYER_VEG)
    pts = [(1514.3 + offset_x, 747.1 + offset_y, 0.0), (1614.2 + offset_x, 794.8 + offset_y, 0.0), (1675.7 + offset_x, 747.1 + offset_y, 0.0), (1627.0 + offset_x, 701.0 + offset_y, 0.0), (1550.1 + offset_x, 654.9 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_VEG): rs.AddLayer(LAYER_VEG)
    rs.CurrentLayer(LAYER_VEG)
    pts = [(1826.8 + offset_x, 724.1 + offset_y, 0.0), (1875.5 + offset_x, 840.9 + offset_y, 0.0), (1952.4 + offset_x, 887.0 + offset_y, 0.0), (1975.4 + offset_x, 654.9 + offset_y, 0.0), (1952.4 + offset_x, 493.5 + offset_y, 0.0), (1826.8 + offset_x, 608.8 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(1063.3 + offset_x, 690.3 + offset_y, 0.0), (1176.0 + offset_x, 736.4 + offset_y, 0.0), (1301.6 + offset_x, 771.7 + offset_y, 0.0), (1427.1 + offset_x, 794.8 + offset_y, 0.0), (1550.1 + offset_x, 817.9 + offset_y, 0.0), (1675.7 + offset_x, 840.9 + offset_y, 0.0), (1801.2 + offset_x, 864.0 + offset_y, 0.0), (1926.8 + offset_x, 887.0 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(1176.0 + offset_x, 759.4 + offset_y, 0.0), (1201.7 + offset_x, 654.9 + offset_y, 0.0), (1224.7 + offset_x, 539.6 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(1550.1 + offset_x, 805.6 + offset_y, 0.0), (1575.7 + offset_x, 724.1 + offset_y, 0.0), (1601.4 + offset_x, 631.8 + offset_y, 0.0), (1627.0 + offset_x, 515.0 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(1875.5 + offset_x, 864.0 + offset_y, 0.0), (1901.1 + offset_x, 724.1 + offset_y, 0.0), (1926.8 + offset_x, 608.8 + offset_y, 0.0), (1901.1 + offset_x, 493.5 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    rs.CurrentLayer(original_layer)
    rs.EnableRedraw(True)
    print('Diagram drawn for Klyde Warren Park.')


# --- Run immediately when executed via RunPythonScript ---
draw_diagram_klyde_warren_park()