# -*- coding: utf-8 -*-
# Auto-generated by ai_vision_tracer.py for: Federation Square
# Image size : 1100 x 660 px
# Scale      : 3.28084 Rhino units per metre
# Diagram BL : (0, 0, 0)  ->  TR : (1702.5, 1021.5, 0)
# The map image MUST be placed with its bottom-left corner at world origin
# and its top-right at the TR coordinates above.

import rhinoscriptsyntax as rs

LAYER_PLAZA = 'Diagram::Plaza_Boundary'
LAYER_VEG   = 'Diagram::Vegetation'
LAYER_PATHS = 'Diagram::Paths'

def draw_diagram_federation_square(offset_x=0.0, offset_y=0.0):
    rs.EnableRedraw(False)
    original_layer = rs.CurrentLayer()

    if not rs.IsLayer(LAYER_PLAZA): rs.AddLayer(LAYER_PLAZA)
    rs.CurrentLayer(LAYER_PLAZA)
    pts = [(301.3 + offset_x, 832.5 + offset_y, 0.0), (1409.6 + offset_x, 832.5 + offset_y, 0.0), (1409.6 + offset_x, 142.0 + offset_y, 0.0), (301.3 + offset_x, 142.0 + offset_y, 0.0), (301.3 + offset_x, 832.5 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_VEG): rs.AddLayer(LAYER_VEG)
    rs.CurrentLayer(LAYER_VEG)
    pts = [(335.4 + offset_x, 681.3 + offset_y, 0.0), (1373.9 + offset_x, 681.3 + offset_y, 0.0), (1373.9 + offset_x, 454.6 + offset_y, 0.0), (335.4 + offset_x, 454.6 + offset_y, 0.0), (335.4 + offset_x, 681.3 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_VEG): rs.AddLayer(LAYER_VEG)
    rs.CurrentLayer(LAYER_VEG)
    pts = [(335.4 + offset_x, 416.8 + offset_y, 0.0), (1373.9 + offset_x, 416.8 + offset_y, 0.0), (1373.9 + offset_x, 179.8 + offset_y, 0.0), (335.4 + offset_x, 179.8 + offset_y, 0.0), (335.4 + offset_x, 416.8 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(335.4 + offset_x, 709.9 + offset_y, 0.0), (1373.9 + offset_x, 709.9 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(335.4 + offset_x, 435.2 + offset_y, 0.0), (1373.9 + offset_x, 435.2 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    rs.CurrentLayer(original_layer)
    rs.EnableRedraw(True)
    print('Diagram drawn for Federation Square.')


# --- Run immediately when executed via RunPythonScript ---
draw_diagram_federation_square()