# -*- coding: utf-8 -*-
# Auto-generated by ai_vision_tracer.py for: Gardens by the Bay
# Image size : 1100 x 660 px
# Scale      : 3.28084 Rhino units per metre
# Diagram BL : (0, 0, 0)  ->  TR : (4309.2, 2585.5, 0)
# The map image MUST be placed with its bottom-left corner at world origin
# and its top-right at the TR coordinates above.

import rhinoscriptsyntax as rs

LAYER_PLAZA = 'Diagram::Plaza_Boundary'
LAYER_VEG   = 'Diagram::Vegetation'
LAYER_PATHS = 'Diagram::Paths'

def draw_diagram_gardens_by_the_bay(offset_x=0.0, offset_y=0.0):
    rs.EnableRedraw(False)
    original_layer = rs.CurrentLayer()

    if not rs.IsLayer(LAYER_PLAZA): rs.AddLayer(LAYER_PLAZA)
    rs.CurrentLayer(LAYER_PLAZA)
    pts = [(2120.1 + offset_x, 1052.3 + offset_y, 0.0), (2046.9 + offset_x, 1148.0 + offset_y, 0.0), (2012.4 + offset_x, 1264.3 + offset_y, 0.0), (2012.4 + offset_x, 1398.8 + offset_y, 0.0), (2046.9 + offset_x, 1512.5 + offset_y, 0.0), (2154.6 + offset_x, 1569.4 + offset_y, 0.0), (2335.6 + offset_x, 1590.1 + offset_y, 0.0), (2443.3 + offset_x, 1569.4 + offset_y, 0.0), (2512.2 + offset_x, 1533.2 + offset_y, 0.0), (2551.0 + offset_x, 1473.7 + offset_y, 0.0), (2585.5 + offset_x, 1398.8 + offset_y, 0.0), (2585.5 + offset_x, 1321.2 + offset_y, 0.0), (2551.0 + offset_x, 1207.4 + offset_y, 0.0), (2512.2 + offset_x, 1129.9 + offset_y, 0.0), (2443.3 + offset_x, 1073.0 + offset_y, 0.0), (2335.6 + offset_x, 1034.2 + offset_y, 0.0), (2227.8 + offset_x, 1023.9 + offset_y, 0.0), (2120.1 + offset_x, 1052.3 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_VEG): rs.AddLayer(LAYER_VEG)
    rs.CurrentLayer(LAYER_VEG)
    pts = [(1615.9 + offset_x, 1321.2 + offset_y, 0.0), (1456.5 + offset_x, 1168.6 + offset_y, 0.0), (1417.7 + offset_x, 995.4 + offset_y, 0.0), (1473.7 + offset_x, 824.8 + offset_y, 0.0), (1633.2 + offset_x, 690.3 + offset_y, 0.0), (1865.9 + offset_x, 669.6 + offset_y, 0.0), (2064.1 + offset_x, 747.2 + offset_y, 0.0), (2120.1 + offset_x, 938.5 + offset_y, 0.0), (2046.9 + offset_x, 1129.9 + offset_y, 0.0), (1865.9 + offset_x, 1243.6 + offset_y, 0.0), (1689.2 + offset_x, 1303.1 + offset_y, 0.0), (1615.9 + offset_x, 1321.2 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_VEG): rs.AddLayer(LAYER_VEG)
    rs.CurrentLayer(LAYER_VEG)
    pts = [(2585.5 + offset_x, 1512.5 + offset_y, 0.0), (2801.0 + offset_x, 1628.9 + offset_y, 0.0), (2943.2 + offset_x, 1665.1 + offset_y, 0.0), (3050.9 + offset_x, 1628.9 + offset_y, 0.0), (3050.9 + offset_x, 1512.5 + offset_y, 0.0), (2874.2 + offset_x, 1437.5 + offset_y, 0.0), (2727.7 + offset_x, 1473.7 + offset_y, 0.0), (2585.5 + offset_x, 1512.5 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_VEG): rs.AddLayer(LAYER_VEG)
    rs.CurrentLayer(LAYER_VEG)
    pts = [(2585.5 + offset_x, 1168.6 + offset_y, 0.0), (2801.0 + offset_x, 1091.1 + offset_y, 0.0), (2943.2 + offset_x, 1091.1 + offset_y, 0.0), (3050.9 + offset_x, 1168.6 + offset_y, 0.0), (3050.9 + offset_x, 1282.4 + offset_y, 0.0), (2874.2 + offset_x, 1360.0 + offset_y, 0.0), (2727.7 + offset_x, 1282.4 + offset_y, 0.0), (2585.5 + offset_x, 1168.6 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_VEG): rs.AddLayer(LAYER_VEG)
    rs.CurrentLayer(LAYER_VEG)
    pts = [(2154.6 + offset_x, 669.6 + offset_y, 0.0), (2296.8 + offset_x, 594.7 + offset_y, 0.0), (2512.2 + offset_x, 555.9 + offset_y, 0.0), (2727.7 + offset_x, 594.7 + offset_y, 0.0), (2874.2 + offset_x, 669.6 + offset_y, 0.0), (2943.2 + offset_x, 786.0 + offset_y, 0.0), (2874.2 + offset_x, 899.8 + offset_y, 0.0), (2693.2 + offset_x, 977.3 + offset_y, 0.0), (2443.3 + offset_x, 938.5 + offset_y, 0.0), (2227.8 + offset_x, 861.0 + offset_y, 0.0), (2154.6 + offset_x, 669.6 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_VEG): rs.AddLayer(LAYER_VEG)
    rs.CurrentLayer(LAYER_VEG)
    pts = [(3231.9 + offset_x, 1360.0 + offset_y, 0.0), (3412.9 + offset_x, 1473.7 + offset_y, 0.0), (3589.5 + offset_x, 1551.3 + offset_y, 0.0), (3770.5 + offset_x, 1512.5 + offset_y, 0.0), (3878.2 + offset_x, 1360.0 + offset_y, 0.0), (3912.7 + offset_x, 1207.4 + offset_y, 0.0), (3878.2 + offset_x, 1052.3 + offset_y, 0.0), (3770.5 + offset_x, 977.3 + offset_y, 0.0), (3589.5 + offset_x, 938.5 + offset_y, 0.0), (3412.9 + offset_x, 977.3 + offset_y, 0.0), (3231.9 + offset_x, 1052.3 + offset_y, 0.0), (3197.4 + offset_x, 1207.4 + offset_y, 0.0), (3231.9 + offset_x, 1360.0 + offset_y, 0.0)]
    if len(pts) > 1:
        if len(pts) > 2: pts.append(pts[0])
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(1077.3 + offset_x, 1282.4 + offset_y, 0.0), (1366.0 + offset_x, 1207.4 + offset_y, 0.0), (1508.2 + offset_x, 1168.6 + offset_y, 0.0), (1723.7 + offset_x, 1129.9 + offset_y, 0.0), (1973.6 + offset_x, 1111.8 + offset_y, 0.0), (2154.6 + offset_x, 1129.9 + offset_y, 0.0), (2335.6 + offset_x, 1168.6 + offset_y, 0.0), (2443.3 + offset_x, 1282.4 + offset_y, 0.0), (2477.8 + offset_x, 1437.5 + offset_y, 0.0), (2512.2 + offset_x, 1512.5 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(2443.3 + offset_x, 1282.4 + offset_y, 0.0), (2477.8 + offset_x, 1168.6 + offset_y, 0.0), (2512.2 + offset_x, 1091.1 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(1650.4 + offset_x, 1303.1 + offset_y, 0.0), (1508.2 + offset_x, 1186.7 + offset_y, 0.0), (1473.7 + offset_x, 1016.1 + offset_y, 0.0), (1508.2 + offset_x, 842.9 + offset_y, 0.0), (1650.4 + offset_x, 747.2 + offset_y, 0.0), (1865.9 + offset_x, 708.4 + offset_y, 0.0), (2046.9 + offset_x, 786.0 + offset_y, 0.0), (2081.3 + offset_x, 977.3 + offset_y, 0.0), (2012.4 + offset_x, 1148.0 + offset_y, 0.0), (1865.9 + offset_x, 1264.3 + offset_y, 0.0), (1689.2 + offset_x, 1321.2 + offset_y, 0.0), (1650.4 + offset_x, 1303.1 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(1508.2 + offset_x, 594.7 + offset_y, 0.0), (1796.9 + offset_x, 555.9 + offset_y, 0.0), (2154.6 + offset_x, 555.9 + offset_y, 0.0), (2512.2 + offset_x, 574.0 + offset_y, 0.0), (2874.2 + offset_x, 630.9 + offset_y, 0.0), (3050.9 + offset_x, 708.4 + offset_y, 0.0), (3158.6 + offset_x, 786.0 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(2512.2 + offset_x, 1111.8 + offset_y, 0.0), (2693.2 + offset_x, 1016.1 + offset_y, 0.0), (2874.2 + offset_x, 938.5 + offset_y, 0.0), (3050.9 + offset_x, 899.8 + offset_y, 0.0), (3231.9 + offset_x, 861.0 + offset_y, 0.0), (3412.9 + offset_x, 824.8 + offset_y, 0.0), (3589.5 + offset_x, 786.0 + offset_y, 0.0), (3770.5 + offset_x, 747.2 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    if not rs.IsLayer(LAYER_PATHS): rs.AddLayer(LAYER_PATHS)
    rs.CurrentLayer(LAYER_PATHS)
    pts = [(3231.9 + offset_x, 1282.4 + offset_y, 0.0), (3374.1 + offset_x, 1398.8 + offset_y, 0.0), (3555.1 + offset_x, 1437.5 + offset_y, 0.0), (3736.0 + offset_x, 1398.8 + offset_y, 0.0), (3843.8 + offset_x, 1282.4 + offset_y, 0.0), (3878.2 + offset_x, 1168.6 + offset_y, 0.0), (3843.8 + offset_x, 1052.3 + offset_y, 0.0), (3736.0 + offset_x, 1016.1 + offset_y, 0.0), (3555.1 + offset_x, 1052.3 + offset_y, 0.0), (3374.1 + offset_x, 1129.9 + offset_y, 0.0), (3231.9 + offset_x, 1168.6 + offset_y, 0.0), (3231.9 + offset_x, 1282.4 + offset_y, 0.0)]
    if len(pts) > 1:
        rs.AddPolyline(pts)

    rs.CurrentLayer(original_layer)
    rs.EnableRedraw(True)
    print('Diagram drawn for Gardens by the Bay.')


# --- Run immediately when executed via RunPythonScript ---
draw_diagram_gardens_by_the_bay()