import os
import sys
import json
import math
import argparse
try:
    import cv2
    import numpy as np
except ImportError:
    pass

try:
    from dotenv import load_dotenv
    from google import genai
    from google.genai import types
except ImportError as e:
    print(f"❌ Missing dependency: {e}. Please run: pip install python-dotenv google-genai")
    sys.exit(1)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(BASE_DIR)

from logic.precedent_scraper import SITES

def trace_plaza_boundary(site_id, custom_img=None, custom_lat=None, custom_zoom=18.0):
    load_dotenv(os.path.join(BASE_DIR, '.env'))
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        print("❌ Error: GEMINI_API_KEY missing.")
        return
        
    client = genai.Client(api_key=api_key)
    
    if custom_img and custom_lat is not None:
        img_path = custom_img
        lat = custom_lat
        zoom = custom_zoom
        site_name = site_id
    else:
        site_data = next((s for s in SITES if s['name'].lower() == site_id.lower() or s['id'] == site_id.lower().replace(' ', '_')), None)
        if not site_data:
            print(f"❌ Error: Site '{site_id}' not found in registry.")
            return
        img_path = os.path.join(BASE_DIR, 'assets', 'precedents', f"{site_data['id']}_satellite.jpg")
        lat = site_data['lat']
        zoom = site_data.get('zoom', 18.0)
        site_name = site_data['name']

    if not os.path.exists(img_path):
        print(f"❌ Error: Satellite image not found at {img_path}")
        return
        
    print(f"👁️  Sending {site_name} satellite image to Gemini Vision for boundary tracing...")
    
    with open(img_path, "rb") as f:
        img_bytes = f.read()
        
    # --- Generate Canny Edge Map via OpenCV ---
    print("🧠 Processing image through Canny Edge Detection...")
    img_cv = cv2.imread(img_path)
    gray = cv2.cvtColor(img_cv, cv2.COLOR_BGR2GRAY)
    blurred = cv2.GaussianBlur(gray, (5, 5), 0)
    edges = cv2.Canny(blurred, 50, 150)
    kernel = np.ones((2,2), np.uint8)
    edges_thick = cv2.dilate(edges, kernel, iterations=1) # Thicken lines for the AI
    _, edge_buffer = cv2.imencode('.jpg', edges_thick)
    edge_bytes = edge_buffer.tobytes()
    
    prompt = """
    You are an expert architectural diagrammer analyzing a satellite image of a public space.
    Your task is to generate a full spatial diagram matching an abstract, analytical style (similar to your analysis of Parc de la Villette and Schouwburgplein).
    
    You have been provided with TWO images: 
    1. The raw satellite view.
    2. A Canny Edge map. Use the high-contrast lines in the edge map to accurately lock your coordinates to the true physical boundaries, paths, and hardscape edges.
    
    Extract the following spatial elements as series of (x, y) coordinates.
    The coordinates MUST be normalized between 0.0 and 1.0, where:
    [0.0, 0.0] is the Top-Left corner of the image.
    [1.0, 1.0] is the Bottom-Right corner of the image.
    
    Return ONLY a valid JSON object with NO markdown formatting, containing these keys:
    1. "plaza_boundary": A single array of points for the main hardscape/plaza perimeter.
    2. "vegetation_zones": An array of multiple point arrays representing distinct green spaces/parks.
    3. "paths": An array of multiple point arrays representing major pedestrian axes or circulation routes.
    
    Example format:
    {
      "plaza_boundary": [[0.5, 0.2], [0.6, 0.3], [0.55, 0.8]],
      "vegetation_zones": [ [[0.1, 0.1], [0.2, 0.1], [0.15, 0.2]] ],
      "paths": [ [[0.0, 0.5], [1.0, 0.5]] ]
    }
    """
    
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=[
            prompt,
            types.Part.from_bytes(data=img_bytes, mime_type="image/jpeg"),
            types.Part.from_bytes(data=edge_bytes, mime_type="image/jpeg")
        ]
    )
    
    try:
        clean_json = response.text.strip().replace("```json", "").replace("```", "")
        data = json.loads(clean_json)
        print(f"✅ Gemini successfully extracted diagrammatic geometry.")
    except Exception as e:
        print(f"❌ Failed to parse Gemini response: {e}\nResponse:\n{response.text}")
        return
        
    # --- Override layers to match existing system ---
    L_PLAZA  = "Hardscape Plaza"
    L_VEG    = "Green Space"
    L_PATHS  = "Pedestrian Pathways"
    L_STREET = "Streets"

    # --- Generate Rhino Python script ---
    safe_name = site_name.lower().replace(' ', '_').replace(',', '').replace('.', '')
    out_dir   = os.path.join(BASE_DIR, 'data', 'orchestrator_scripts')
    out_path  = os.path.join(out_dir, f"draw_diagram_{safe_name}.py")

    script_lines = [
        "# -*- coding: utf-8 -*-",
        f"# Auto-generated by ai_vision_tracer.py for: {site_name}",
        "import rhinoscriptsyntax as rs",
        "",
        f"LAYER_PLAZA  = {repr(L_PLAZA)}",
        f"LAYER_VEG    = {repr(L_VEG)}",
        f"LAYER_PATHS  = {repr(L_PATHS)}",
        f"LAYER_STREET = {repr(L_STREET)}",
        "",
        "def get_map_bounds():",
        "    # Find the picture frame surface to align coordinates",
        "    srfs = rs.ObjectsByType(8) # Surfaces",
        "    if not srfs: return 0, 0, 100, 100",
        "    # Assume the largest surface is the map",
        "    map_srf = sorted(srfs, key=lambda s: rs.SurfaceArea(s)[0], reverse=True)[0]",
        "    bbox = rs.BoundingBox(map_srf)",
        "    return bbox[0].X, bbox[0].Y, bbox[2].X - bbox[0].X, bbox[2].Y - bbox[0].Y",
        "",
        f"def draw_diagram_{safe_name}():",
        "    rs.EnableRedraw(False)",
        "    original_layer = rs.CurrentLayer()",
        "",
        "    ox, oy, w, h = get_map_bounds()",
        "    print('Map bounds: Origin({:.1f}, {:.1f}) Size({:.1f}x{:.1f})'.format(ox, oy, w, h))",
        "    ",
        "    def map_pt(u, v):",
        "        # v is flipped because image UV has 0,0 at top-left, Rhino has 0,0 at bottom-left",
        "        return (ox + u * w, oy + (1.0 - v) * h, 0.0)",
        ""
    ]

    def ensure_layer_code(layer_const):
        """Emit lines that create the layer only if it doesn't already exist."""
        return [
            f"    if not rs.IsLayer({layer_const}): rs.AddLayer({layer_const})",
            f"    rs.CurrentLayer({layer_const})",
        ]

    def add_poly_code(pts_array, layer_const, close=True):
        if not pts_array:
            return
        script_lines.extend(ensure_layer_code(layer_const))
        
        script_lines.append("    pts = [")
        for u, v in pts_array:
            script_lines.append(f"        map_pt({u}, {v}),")
        script_lines.append("    ]")
        
        script_lines.append("    if len(pts) > 1:")
        if close:
            script_lines.append("        if len(pts) > 2: pts.append(pts[0])")
        script_lines.append("        rs.AddPolyline(pts)")
        script_lines.append("")

    # Plaza boundary
    plaza = data.get("plaza_boundary", [])
    if plaza:
        add_poly_code(plaza, "LAYER_PLAZA", close=True)

    # Vegetation zones
    for veg in data.get("vegetation_zones", []):
        add_poly_code(veg, "LAYER_VEG", close=True)

    # Paths
    for path in data.get("paths", []):
        add_poly_code(path, "LAYER_PATHS", close=False)

    script_lines.extend([
        "    rs.CurrentLayer(original_layer)",
        "    rs.EnableRedraw(True)",
        f"    print('Diagram drawn for {site_name}.')",
        "",
        "if __name__ == '__main__':",
        f"    draw_diagram_{safe_name}()"
    ])

    with open(out_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(script_lines))

    print(f"Script generated: {out_path}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--site", type=str, required=True, help="Site name (e.g., 'Piazza del Campo')")
    parser.add_argument("--image", type=str, help="Direct path to image", default=None)
    parser.add_argument("--lat", type=float, help="Latitude for scale", default=None)
    parser.add_argument("--zoom", type=float, help="Zoom level", default=18.0)
    args = parser.parse_args()
    trace_plaza_boundary(args.site, args.image, args.lat, args.zoom)