"""
logic/kohya_configs.py
-----------------------
Generates kohya_ss (sd-scripts) training configs for the Pershing LoRA
experiment (2026-07-29).

WHY GENERATED RATHER THAN CHECKED IN AS STATIC FILES: a kohya dataset TOML
needs an absolute image_dir, and this repo lives on three Syncthing-synced
machines with different drive letters -- a committed TOML with D:\\... baked
in is the exact failure this project already fixed in its data loaders and
comfy client. Generating them puts the machine-specific part where it
belongs and keeps the experimental design (below) version-controlled.

WHY ONE HYPERPARAMETER BLOCK: the collapsed/controlled comparison is only
meaningful if the two runs differ in NOTHING except their captions. Learning
rate, seed, steps, network dim and scheduler are defined once in TRAIN_ARGS
and emitted verbatim into every run, so the two cannot drift by hand-editing
one command and forgetting the other. That drift is the single easiest way
to invalidate this experiment, and it is invisible after the fact.

VRAM: sized for a 12GB card (RTX 5070) training SDXL. gradient checkpointing
+ cached latents + 8-bit AdamW + bf16 are all load-bearing here, not
optional tuning. If it still OOMs, see the two documented fallbacks in the
generated runner -- in preference order, since the first costs less
experimental validity than the second.

Run:
    .venv/Scripts/python.exe logic/kohya_configs.py
    .venv/Scripts/python.exe logic/kohya_configs.py --steps 3000 --dim 16
"""
import argparse
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATASET_DIR = os.path.join(BASE_DIR, "data", "lora_datasets", "pershing")
OUT_DIR = os.path.join(DATASET_DIR, "kohya")
LORA_OUT = os.path.join(DATASET_DIR, "trained")

# The three training variants. collapsed/controlled are the experiment;
# coherent is a single-era reference point.
VARIANTS = ("collapsed", "controlled", "coherent")

DEFAULT_BASE_MODEL = os.path.join(
    "D:", os.sep, "ComfyUI_windows_portable", "ComfyUI", "models", "checkpoints",
    "juggernautXL_ragnarokBy.safetensors")

# Single source of truth for everything that must be identical across runs.
# Anything genuinely per-run (dataset path, output name) is NOT in here.
TRAIN_ARGS = {
    "network_module": "networks.lora",
    "network_dim": 32,
    "network_alpha": 16,
    "learning_rate": "1e-4",
    "unet_lr": "1e-4",
    # Lower than the UNet rate, the usual convention -- the text encoder
    # overfits fast and a hot TE is how a trigger token starts hijacking
    # unrelated prompts.
    "text_encoder_lr": "5e-5",
    "optimizer_type": "AdamW8bit",
    "lr_scheduler": "cosine",
    "lr_warmup_steps": 100,
    "max_train_steps": 2000,
    # The decay series depends on these intermediates existing. Without
    # this flag the run produces only a final file and --mode checkpoints
    # has nothing to sweep.
    "save_every_n_steps": 250,
    "mixed_precision": "bf16",
    "save_precision": "bf16",
    "seed": 20260728,
    "max_data_loader_n_workers": 1,
    "save_model_as": "safetensors",
}

# Flags with no value. gradient_checkpointing and the latent caches are the
# difference between fitting in 12GB and not.
TRAIN_FLAGS = [
    "gradient_checkpointing",
    "cache_latents",
    "cache_latents_to_disk",
    # SDXL's VAE produces NaNs in fp16; harmless with bf16 but kept because
    # the failure it prevents is a silently black output half an hour in.
    "no_half_vae",
    # sdpa (PyTorch's built-in scaled dot-product attention) rather than
    # xformers, deliberately. xformers ships as a separate wheel pinned to a
    # specific torch build, and this setup has to force-reinstall torch into
    # kohya's venv to get sm_120 (Blackwell) support -- which is exactly the
    # situation that leaves xformers mismatched and failing at import or
    # crashing mid-run. sdpa is part of torch, so it cannot fall out of sync,
    # and on modern torch the speed difference is minor.
    "sdpa",
]

DATASET_TOML = """# Generated by logic/kohya_configs.py -- do not hand-edit.
# Regenerate instead, so collapsed/controlled cannot drift apart.

[general]
# Captions are the independent variable in this experiment, so they are used
# exactly as written: no shuffling, no dropout, no appended class token.
shuffle_caption = false
caption_extension = ".txt"
keep_tokens = 1

[[datasets]]
resolution = {resolution}
batch_size = 1
enable_bucket = true
bucket_no_upscale = true
min_bucket_reso = 512
max_bucket_reso = 2048

  [[datasets.subsets]]
  image_dir = '{image_dir}'
  num_repeats = 1
"""

RUNNER = r"""@echo off
REM Generated by logic/kohya_configs.py -- do not hand-edit.
REM
REM Trains one variant of the Pershing LoRA experiment. Every hyperparameter
REM below is emitted from a single block in that script, so the collapsed and
REM controlled runs are guaranteed identical except for their captions. If you
REM edit a value here, edit it there and regenerate, or the comparison is void.
REM
REM   train_lora.bat collapsed
REM   train_lora.bat controlled
REM   train_lora.bat coherent
REM
REM Close ComfyUI first -- {vram}GB will not hold a training run and a
REM diffusion server at the same time.
REM
REM IF IT RUNS OUT OF MEMORY, in preference order:
REM   1) add  --network_train_unet_only   (skips text-encoder training; the
REM      caption ablation still works because captions still condition the
REM      UNet, it just binds the trigger token less hard)
REM   2) drop resolution to 768 in the dataset TOML (cheaper, but 768 is off
REM      SDXL's native distribution and changes what the model learns, so it
REM      costs more experimental validity than option 1)

setlocal
if "%~1"=="" (echo Usage: train_lora.bat [collapsed^|controlled^|coherent] & exit /b 1)
set VARIANT=%~1

set KOHYA_DIR={kohya_dir}
set BASE_MODEL={base_model}
set DATASET_CFG={out_dir}\dataset_%VARIANT%.toml
set OUTPUT_DIR={lora_out}\%VARIANT%
REM Full path to the venv's accelerate, NOT a bare `accelerate`. kohya's
REM venv is never activated by this script, so relying on PATH fails with
REM "'accelerate' is not recognized" (exit 9009).
set ACCELERATE={accelerate}

if not exist "%KOHYA_DIR%\sdxl_train_network.py" (
  echo ERROR: kohya_ss sd-scripts not found at %KOHYA_DIR%
  echo Set KOHYA_DIR at the top of this file, or regenerate with:
  echo   python logic/kohya_configs.py --kohya-dir "C:\path\to\kohya_ss\sd-scripts"
  exit /b 1
)
if not exist "%ACCELERATE%" (
  echo ERROR: accelerate not found at %ACCELERATE%
  echo Expected it inside kohya_ss's venv. If your install uses a different
  echo venv location, regenerate with --kohya-dir pointing at sd-scripts.
  exit /b 1
)
if not exist "%BASE_MODEL%" (echo ERROR: base model not found: %BASE_MODEL% & exit /b 1)
if not exist "%DATASET_CFG%" (echo ERROR: dataset config not found: %DATASET_CFG% & exit /b 1)

if not exist "%OUTPUT_DIR%" mkdir "%OUTPUT_DIR%"

REM sd-scripts prints bilingual Japanese/English status lines. On a default
REM Windows console (cp1252) the very first one -- "running training /
REM <jp>", emitted immediately before the training loop -- raises
REM UnicodeEncodeError and kills the run after the model has loaded, the
REM dataset has parsed and latents have cached. It looks like a training
REM failure and is purely a console-encoding one. UTF-8 mode fixes it.
set PYTHONUTF8=1
set PYTHONIOENCODING=utf-8

pushd "%KOHYA_DIR%"
"%ACCELERATE%" launch --num_cpu_threads_per_process 2 sdxl_train_network.py ^
  --pretrained_model_name_or_path="%BASE_MODEL%" ^
  --dataset_config="%DATASET_CFG%" ^
  --output_dir="%OUTPUT_DIR%" ^
  --output_name=pershing_%VARIANT% ^
{args}
set TRAIN_EXIT=%ERRORLEVEL%
popd

REM Check the exit code before claiming success. An earlier version printed
REM "Done" unconditionally, which reported a crashed run as a finished one
REM and sent the user looking for checkpoints in an empty directory.
if not "%TRAIN_EXIT%"=="0" (
  echo.
  echo TRAINING FAILED - exit code %TRAIN_EXIT%. See the error above.
  echo No checkpoints were written to %OUTPUT_DIR%
  exit /b %TRAIN_EXIT%
)

echo.
echo Done. Checkpoints in %OUTPUT_DIR%
echo Symlink or copy them where ComfyUI can see them, then:
echo   python logic/lora_decay_series.py --list-models
endlocal
"""


def find_accelerate(kohya_dir):
    """Locate kohya's venv accelerate.exe.

    sd-scripts lives at <kohya_ss>/sd-scripts, so the venv is one level up.
    Both layouts are probed because setup.bat creates `venv/` while the
    uv-based path (gui-uv.bat, which this repo version also ships) creates
    `.venv/`. Returns the best guess even when nothing is found, so the
    generated runner can report a concrete path in its error rather than
    failing with a bare "not recognized".
    """
    root = os.path.dirname(os.path.abspath(kohya_dir))
    candidates = [
        os.path.join(root, "venv", "Scripts", "accelerate.exe"),
        os.path.join(root, ".venv", "Scripts", "accelerate.exe"),
        os.path.join(root, "venv", "bin", "accelerate"),
    ]
    for c in candidates:
        if os.path.exists(c):
            return c
    return candidates[0]


def generate(kohya_dir, base_model, resolution, overrides):
    args = dict(TRAIN_ARGS)
    args.update({k: v for k, v in overrides.items() if v is not None})
    accelerate = find_accelerate(kohya_dir)

    os.makedirs(OUT_DIR, exist_ok=True)
    os.makedirs(LORA_OUT, exist_ok=True)

    written = []
    for variant in VARIANTS:
        image_dir = os.path.join(DATASET_DIR, variant)
        n = len([f for f in os.listdir(image_dir)
                 if f.lower().endswith((".jpg", ".jpeg", ".png", ".webp"))]) \
            if os.path.isdir(image_dir) else 0
        path = os.path.join(OUT_DIR, f"dataset_{variant}.toml")
        with open(path, "w", encoding="utf8") as f:
            f.write(DATASET_TOML.format(resolution=resolution, image_dir=image_dir))
        written.append((variant, n, path))

    arg_lines = "\n".join(f"  --{k}={v} ^" for k, v in args.items())
    arg_lines += "\n" + "\n".join(f"  --{f} ^" for f in TRAIN_FLAGS[:-1])
    arg_lines += f"\n  --{TRAIN_FLAGS[-1]}"

    runner = os.path.join(OUT_DIR, "train_lora.bat")
    with open(runner, "w", encoding="utf8") as f:
        f.write(RUNNER.format(kohya_dir=kohya_dir, base_model=base_model,
                              out_dir=OUT_DIR, lora_out=LORA_OUT,
                              accelerate=accelerate, args=arg_lines, vram=12))

    print("dataset configs:")
    for variant, n, path in written:
        flag = "" if n else "   <-- EMPTY, run lora_harvest.py captions first"
        print(f"  {variant:<11} {n:>3} images  {os.path.relpath(path, BASE_DIR)}{flag}")
    print(f"\nrunner: {os.path.relpath(runner, BASE_DIR)}")
    print(f"output: {os.path.relpath(LORA_OUT, BASE_DIR)}\\<variant>\\")

    steps, every = args["max_train_steps"], args["save_every_n_steps"]
    print(f"\n{steps} steps, checkpoint every {every} -> {steps // every} intermediates "
          f"per run (what --mode checkpoints sweeps)")
    ok_script = os.path.exists(os.path.join(kohya_dir, "sdxl_train_network.py"))
    ok_accel = os.path.exists(accelerate)
    ok_model = os.path.exists(base_model)
    print("\npreflight:")
    for label, path, ok in (("sd-scripts", kohya_dir, ok_script),
                            ("accelerate", accelerate, ok_accel),
                            ("base model", base_model, ok_model)):
        print(f"  [{'ok' if ok else 'MISSING'}] {label:<11} {path}")
    if not (ok_script and ok_accel and ok_model):
        print("\n  fix the MISSING entries above, then regenerate.")


def main():
    ap = argparse.ArgumentParser(description="Generate kohya_ss configs for the LoRA experiment.")
    ap.add_argument("--kohya-dir", default=os.environ.get(
        "KOHYA_DIR", r"D:\kohya_ss\sd-scripts"))
    ap.add_argument("--base-model", default=DEFAULT_BASE_MODEL)
    ap.add_argument("--resolution", type=int, default=1024)
    ap.add_argument("--steps", type=int, default=None)
    ap.add_argument("--dim", type=int, default=None)
    ap.add_argument("--save-every", type=int, default=None)
    args = ap.parse_args()

    generate(args.kohya_dir, args.base_model, args.resolution, {
        "max_train_steps": args.steps,
        "network_dim": args.dim,
        "save_every_n_steps": args.save_every,
    })


if __name__ == "__main__":
    main()
